meta_product_name: "Air Cut"
meta_title: "Air Cut"
meta_description: "Application pour trouver le meilleur barber"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
